<a href="https://colab.research.google.com/github/mason286/titanic-analysis/blob/main/%E6%95%99%E7%B7%B4%E5%B8%B6%E8%B7%91%E5%8D%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**資料選取**

'''

# - 2. filtered by first column + second column > 50
'''
Your Code
'''

# - 3. filtered by first column < 30 or second column > 30
'''
Your Code
'''

# - 4. filtered by total sum of row > 100
'''
Your Code
'''

In [ ]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# - 1. filtered by first column > 20?
print(df[df[0]>20])

     0   1   2   3
0   29  12  37  11
2   26  23  38  26
8   25  10  38  33
9   38  24  31  33
10  31  21  26  14
13  30  39  26  10

In [ ]:
# prompt: filtered by first column + second column > 50

df[df[0] + df[1] > 50]

     0   1   2   3
9   38  24  31  33
10  31  21  26  14
12  19  38  32  21
13  30  39  26  10

In [ ]:
#- 3. filtered by first column < 30 or second column > 30
print(df[(df[0]<30)|(df[1]>30)])

     0   1   2   3
1   21  26  10  11
3   15  16  11  37
4   14  22  29  25
5   20  11  13  16
7   17  30  38  29
8   21  13  35  37
9   26  26  10  16
11  33  35  35  22
12  36  35  10  15
13  25  19  36  21
14  21  13  28  18

In [ ]:
#- 4. filtered by total sum of row > 100
df[df.sum(axis=1)>100]

     0   1   2   3
0   38  29  32  25
2   31  29  37  13
6   34  29  22  24
7   17  30  38  29
8   21  13  35  37
10  37  10  26  32
11  33  35  35  22
13  25  19  36  21

資料匯總
請利用 Pandas 計算給定的資料中不同 weekday 的 visitor 總和為何

In [ ]:
import pandas as pd
import numpy as np

d = [
    {'city': 'Austin', 'visitor': 139, 'weekday': 'Sun'},
    {'city': 'Dallas', 'visitor': 237, 'weekday': 'Sun'},
    {'city': 'Austin', 'visitor': 326, 'weekday': 'Mon'},
    {'city': 'Dallas', 'visitor': 456, 'weekday': 'Mon'}
]

In [ ]:
df=pd.DataFrame(d)
grouped = df.groupby('weekday')
result = grouped.agg({'visitor': 'sum'})
print(result)

         visitor
weekday
Mon          782
Sun          376

In [ ]:
import pandas as pd


url="https://raw.githubusercontent.com/kiang/pharmacies/master/data.csv"
df=pd.read_csv(url)
df.head()

,醫事機構代碼,醫事機構名稱,醫事機構種類,電話,地址,分區業務組,特約類別,服務項目,診療科別,終止合約或歇業日期,固定看診時段,備註,TGOS X,TGOS Y,縣市,鄉鎮市區,村里,看診星期
0,5901010058,安郁藥局,藥師自營,(02)25774551,臺北市松山區八德路３段１２巷５１弄１６號１樓,臺北業務組,藥局,-,-,20230529.0,星期一上午看診、星期二上午看診、星期三上午看診、星期四上午看診、星期五上午看診、星期六上午看...,** 我們已經沒賣口罩 **沒賣口罩,121.551182,25.046086,臺北市,松山區,敦化里,NNNNNNYNNNNNNYNNNNNNY
1,5901010076,榮星藥局,藥劑生自營,(02)27124696,臺北市松山區南京東路４段１３３巷５弄１號,臺北業務組,藥局,-,-,20231129.0,星期一上午看診、星期二上午看診、星期三上午看診、星期四上午看診、星期五上午看診、星期六上午看...,-,121.555235,25.052137,臺北市,松山區,東勢里,NNNNNNNNNNNNNNNNNNNNY
2,5901010085,安世藥局,藥師自營,(02)27133405,臺北市松山區南京東路４段１３３巷５弄９號,臺北業務組,藥局,-,-,20230724.0,星期一上午看診、星期二上午看診、星期三上午看診、星期四上午看診、星期五上午看診、星期六上午看...,09:00~22:00,121.555562,25.052140,臺北市,松山區,東勢里,NNNNNNNNNNNNNNNNNNNNY
3,5901010094,明一藥局,藥師自營,(02)27691654,臺北市松山區南京東路５段５９巷２８弄２５號１樓,臺北業務組,藥局,-,-,20230820.0,星期一上午看診、星期二上午看診、星期三上午看診、星期四上午看診、星期五上午看診、星期六上午看...,AM10: ~~PM9:00,121.558168,25.052704,臺北市,松山區,東光里,NNNNNNYNNNNNNYNNNNNYY
4,5901010165,傑安藥局,藥師自營,(02)27524155,臺北市松山區八德路２段４３７巷７弄８號１樓,臺北業務組,藥局,-,-,20230215.0,星期一上午看診、星期二上午看診、星期三上午看診、星期四上午看診、星期五上午看診、星期六上午看...,9:30開始發號碼牌,121.547337,25.049139,臺北市,松山區,中正里,NNNNNNYNNNNNNYNNNNNNY

In [ ]:
df.columns

Index(['醫事機構代碼', '醫事機構名稱', '醫事機構種類', '電話', '地址', '分區業務組', '特約類別', '服務項目',
       '診療科別', '終止合約或歇業日期', '固定看診時段', '備註', 'TGOS X', 'TGOS Y', '縣市', '鄉鎮市區',
       '村里', '看診星期'],
      dtype='object')

In [ ]:
facilitycnts=df.groupby('縣市').agg({'醫事機構代碼':'count'})
facilitycnts.sort_values(by='醫事機構代碼',ascending=False)
facilitycnts['醫事機構代碼']>650
facilitycnts[facilitycnts['醫事機構代碼'] > 650]

     醫事機構代碼
縣市
新北市    1256
桃園市     670
臺中市     855
臺北市     780
高雄市     718

In [ ]:
facilitycnts = df.groupby('縣市').agg({'醫事機構代碼':'count'})

facilitycnts = facilitycnts.sort_values(by='醫事機構代碼', ascending=False)

print(facilitycnts['醫事機構代碼'])

縣市
新北市    1256
臺中市     855
臺北市     780
高雄市     718
桃園市     670
臺南市     614
彰化縣     360
雲林縣     252
屏東縣     240
宜蘭縣     143
苗栗縣     142
嘉義縣     137
新竹縣     132
新竹市     129
南投縣     124
基隆市     115
花蓮縣     102
嘉義市      99
臺東縣      47
澎湖縣      15
金門縣       8
連江縣       1
Name: 醫事機構代碼, dtype: int64

In [ ]:
import requests
r= requests.get("https://rate.bot.com.tw/xrt?Lang=zh-TW")
response=r.text

In [ ]:
from  bs4 import BeautifulSoup
d=BeautifulSoup(response)
print(d)

<!DOCTYPE html>
<html class="no-js" lang="zh-TW">
<head>
<meta charset="utf-8"/>
<title>臺灣銀行牌告匯率</title>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="臺灣銀行匯率利率黃金牌價查詢" name="description"/>
<meta content="" name="keywords"/>
<meta content="width=device-width, initial-scale=1, user-scalable=no" name="viewport"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="https://www.bot.com.tw/assets/images/bot-og-image_480x480.png" property="og:image"/>
<meta content="index,follow" name="robots"/>
<link href="/favicon.ico" rel="icon" type="image/x-icon"/>
<link href="/Content/css/font-awesome.min.css" rel="stylesheet"/>
<link href="/Content/css/jquery-ui.min.css" rel="stylesheet"/>
<link href="/Content/main-3.8.0.css" rel="stylesheet"/>
<style nonce="Dgt2dxE76Mr1QRbdPLVEs6JJzf0csoXk9oVhppLvdA4=">
    h1.hero__header { font-size:1.5625rem }


    .bank {display:none}
    </style>
<noscript>
<style>
            table th.noscript {
                display: table-cell;
            }

            table th.hasscript {
                display: none;
            }

            table td.noscript {
                display: table-cell;
            }

            table td.hasscript {
                display: none;
            }

            .btn.noscript {
                display: inline-block;
            }

            .btn.hasscript {
                display: none;
            }

            .hasscript-div {
                display: none;
            }
        </style>
</noscript>
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-4E35HTJ2CY"></script>
<script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-4E35HTJ2CY');
    </script>
<!-- Google Analytics -->
<script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
        ga('create', 'UA-122091737-1', 'auto');
        ga('send', 'pageview');
    </script>
</head>
<body class="undefined">
<a class="sr-only sr-only-focusable" href="#h1_id" title="跳至主要內容">跳至主要內容</a>
<div class="page-wrapper">
<main class="main" role="main">
<noscript><div class="container text-center">您的瀏覽器不支援JavaScript功能，若網頁功能無法正常使用時，請開啟瀏覽器JavaScript狀態。</div></noscript>
<div class="hero container">
<nav>
<div class="nav_ctn">
<div class="hidden-print hero__banner">
<img alt="臺灣銀行logo" src="/Content/images/logo.png" title="臺灣銀行logo"/>
<div class="search">
<form action=".">
<label for="search">關鍵字查詢</label>
<button aria-button="查詢" class="fa fa-search" type="submit">查詢</button>
<input id="search" name="search" type="search"/>
</form>
</div>
</div>
<div class="TitleLang">
<div class="dropdown_lang_Select hidden-print">
<div>
<select class="lang_ddl hasscript-div" id="lang_ddl" title="語系選擇">
<option value="zh-TW">正體中文</option>
<option value="zh-CN">简体中文</option>
<option value="en-US">English</option>
<!--<option value="ja-JP">日本語</option>-->
</select>
<noscript>
<ul>
<li><a href="?Lang=zh-TW">正體中文</a></li>
</ul>
</noscript>
</div>
</div>
<div class="dropdown_lang_CSS">
<div>
<div class="dropdown dropdown_lang hasscript-div">
<button class="dropbtn" id="lang_ddl_phone">中</button>
<div class="dropdown-content">
<a class="lang_ddl_css" data-value="zh-TW">正體中文</a>
<a class="lang_ddl_css" data-value="zh-CN">简体中文</a>
<a class="lang_ddl_css" data-value="en-US">English</a>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
</div>
<nav class="container hidden-print"><a href="/">首頁</a> / 牌告匯率</nav>
<div class="container H1_div_ctrl clr">
<div class="logo_div">
<img alt="臺灣銀行logo" src="/Content/images/logo_color.png" title="臺灣銀行logo" width="200"/>
</div>
<h1>
<span class="logo"></span>
<span class="color-blue" id="h1_small_id">2024/07/08</span>
<span class="nowrap" id="h1_id"><span class="color-blue">本行</span><span class="color-red">非營業時間</span><span class="color-blue">牌告匯率</span></span>
</h1>
<div class="nav-share">
                        | <a href="/home/Sitemap" target="_blank" title="網站導覽(另開視窗)">網站導覽</a>
                        | <a href="https://www.bot.com.tw" target="_blank" title="臺灣銀行首頁(另開視窗)">臺銀首頁</a>
|                             <a class="share share_fb" href="" title="分享至Facebook (另開視窗)"><img alt="分享至Facebook" src="/Content/images/FB.png"/></a>
<a class="share share_line" href="" title="分享至Line (另開視窗)"><img alt="分享至Line" src="/Content/images/LINE.png"/></a>
</div>
</div>
<div class="container" id="ie10andbelow">
                本行匯率利率黃金牌價服務僅支援下列瀏覽器，若您使用IE10 (含) 以下版本瀏覽器，建議您升級您的IE瀏覽器，或使用其他瀏覽器軟體如 Google Chrome、Mozilla Firefox，以獲得最佳瀏覽體驗。
                <br/><br/>
<div class="ie10-indent">Windows 作業系統：Internet Explorer 11、Microsoft Edge、Google Chrome、Mozilla Firefox 瀏覽器。</div>
<div class="ie10-indent">Macintosh (MAC) 作業系統：Safari 瀏覽器。</div>
<br/>
<div class="color-red">如您使用IE11瀏覽器出現此頁面，請您檢視瀏覽器「工具」之「相容性檢視」設定是否開啟，請將之關閉。</div>
                您可於以下連結下載升級您的 Microsoft Internet Explorer 瀏覽器，或下載 Google Chrome、Mozilla Firefox瀏覽器。
                <hr class="hr-grey"/>
<a class="browser" href="https://support.microsoft.com/" target="_blank" title="IE (另開視窗)">
<img alt="IE" src="/Content/images/browser-ie.png" width="90"/><br/><br/>
<div>Internet Explorer</div>
</a>
<a class="browser" href="https://www.google.com/intl/zh-TW/chrome/" target="_blank" title="Chrome (另開視窗)">
<img alt="Chrome" src="/Content/images/browser-chrome.png" width="90"/><br/><br/>
<div>Google Chrome</div>
</a>
<a class="browser" href="https://www.mozilla.org/zh-TW/firefox/new/" target="_blank" title="Firefox (另開視窗)">
<img alt="Firefox" src="/Content/images/browser-firefox.png" width="90"/><br/><br/>
<div>Mozilla Firefox</div>
</a>
<a class="browser" href="https://support.apple.com/zh_TW/downloads/safari" target="_blank" title="Safari (另開視窗)">
<img alt="Safari" src="/Content/images/browser-safari.png" width="90"/><br/><br/>
<div>Mac Safari</div>
</a>
</div>
<div id="ie11andabove">
<style nonce="WAZMYix7wAG4IwwrpeT0bXxLJwvI6b0v/9Bcvuc26nA=">
    .table td.text-right {position:relative; white-space:nowrap}
    .table form {display:inline}
    .bank {left:17px; margin:0; padding:0 6px; right:auto}
    :lang(en-US) .bank {left:15px}
    .xrt-currency {min-width:85px}
    .xrt-rate {min-width:220px}
    .xrt-cur-indent {text-indent:30px}
    @media (max-width: 1200px) {a.bank {left:5px}}
	@media (max-width: 979px) {.bank {display:none}}
	@media (max-width: 767px) {.bank {display:inline; position:static} .table form {float:left; margin:0}}
	@media (max-width: 550px) {.bank {font-size:0.6875rem; padding:0 2px; display:block}}
</style>
<div class="container">
<dl class="dl-horizontal" title="注意事項">
<dt><span class="bulletin-text" color="#0000ff"><span class="bulletin-text">請注意：</span> </span></dt>
<dd>
<ol>
<li><span class="bulletin-text" color="#0000ff"><span class="bulletin-text" color="#0000ff">本表資料僅供參考，不代表實際交易匯率。 </span></span></li>
<li><span class="bulletin-text" color="#0000ff"><span class="bulletin-text" color="#0000ff">「網路銀行」及「Easy購線上申購現鈔」之實際交易匯率，以交易時顯示之匯率為準。 </span></span></li>
<li><span class="bulletin-text" color="#0000ff"><span class="bulletin-text" color="#0000ff">臨櫃實際交易匯率以交易時本行匯率為準。 </span></span></li>
<li><span class="bulletin-text" color="#0000ff"><span class="bulletin-text" color="#0000ff">本網頁牌告匯率資訊為靜態顯示，顯示之牌告匯率資訊不會隨後續異動而自動更新資訊，欲得知本行最新牌告匯率資訊請按「取得最新報價」鈕。 </span></span></li>
<li><span class="bulletin-text" color="#0000ff"><span class="bulletin-text" color="#0000ff">本頁面匯率資訊於本行營業時間係顯示「本行營業時間牌告匯率」，於本行非營業時間係顯示「本行非營業時間匯率」，如欲查詢本行歷史匯率資訊，請至<span class="break-word"><a href="https://rate.bot.com.tw/xrt/history?Lang=zh-TW" target="_blank">「歷史匯率查詢(另開視窗)」</a></span>。</span></span></li>
</ol>
</dd>
</dl>
<p class="text-right">
<a class="btn right click_reload" href="">取得最新報價</a>
<a class="btn right" href="/trial/t14" target="_blank" title="匯率試算 (另開視窗)">匯率試算</a>
<a class="btn right" href="https://fctc.bot.com.tw/" target="_blank" title="線上申購外幣現鈔  (另開視窗)">線上申購外幣現鈔</a>
</p>
<p class="text-info">
<span class="fa fa-desktop"></span>
        牌價最新掛牌時間：<span class="time">2024/07/09 07:11</span>
</p>
<p class="visible-phone btn-group print_hide" id="rate-toggles">
<button class="rate-toggle-cash active print_hide btn hasscript-div" type="button">現金匯率</button>
<button class="rate-toggle-sight print_hide btn hasscript-div" type="button">即期匯率</button>
</p>
<table class="table table-striped table-bordered table-condensed table-hover" summary="此表格是牌告匯率，表格分為七直欄，第一直欄是幣別，第二直欄是本行買入現金匯率，第三直欄是本行賣出現金匯率，第四直欄是本行買入即期匯率，第五直欄是本行賣出即期匯率，第六直欄是遠期匯率連結，第七直欄是歷史匯率連結。" title="牌告匯率">
<thead class="phone-medium-font">
<tr>
<th class="print_width set-title-L-min-width-class noscript" rowspan="2" scope="auto">幣別</th>
<th class="print_width rowSP_Ctrl_2_2_2 set-title-L-min-width-class hasscript xrt-currency" scope="auto">幣別</th>
<th class="print_hide rate-content-cash xrt-rate" colspan="2" scope="auto">現金匯率</th>
<th class="hidden" scope="auto"></th>
<th class="print_hide rate-content-sight xrt-rate" colspan="2" scope="auto">即期匯率</th>
<th class="hidden" scope="auto"></th>
<th class="print_hide" rowspan="2" scope="auto"><span class=""><span>遠期匯率</span></span></th>
<th class="print_hide noscript" rowspan="2" scope="auto">歷史匯率</th>
<th class="print_hide rowSP_Ctrl_2_2_2 hasscript" scope="auto">歷史匯率</th>
<th class="display_none_print_show print_width" colspan="2" scope="auto">現金匯率</th>
<th class="hidden" scope="auto"></th>
<th class="display_none_print_show print_width" colspan="2" scope="auto">即期匯率</th>
<th class="hidden" scope="auto"></th>
</tr>
<tr>
<th class="hidden" scope="auto"></th>
<th class="rate-content-cash print_hide" scope="auto">
<span class="width-inherit">
<span class="">本行買入</span>
</span>
</th>
<th class="rate-content-cash print_hide" scope="auto">
<span class="width-inherit">
<span class="">本行賣出</span>
</span>
</th>
<th class="rate-content-sight print_hide" data-hide="phone" scope="auto">
<span class="width-inherit">
<span class="">本行買入</span>
</span>
</th>
<th class="rate-content-sight print_hide" data-hide="phone" scope="auto">
<span class="width-inherit">
<span class="">本行賣出</span>
</span>
</th>
<th class="hidden" scope="auto"></th>
<th class="display_none_print_show print_width" scope="auto"><span class="width-inherit">本行買入</span></th>
<th class="display_none_print_show print_width" scope="auto"><span class="width-inherit">本行賣出</span></th>
<th class="display_none_print_show print_width" scope="auto"><span class="width-inherit">本行買入</span></th>
<th class="display_none_print_show print_width" scope="auto"><span class="width-inherit">本行賣出</span></th>
</tr>
</thead>
<tbody>
<tr>
<td class="currency phone-small-font" data-table="幣別">
<div>
<div class="sp-div sp-america-div">
<img alt="美金" class="sp-img sp-america-img" src="/Content/images/sprite_lateral.png" title="幣別國旗"/>
</div>
<br class="visible-phone print_hide"/>
<div class="visible-phone print_hide">
                                美金 (USD)
                            </div>
<div class="hidden-phone print_show xrt-cur-indent">
                                美金 (USD)
                            </div>
</div>
</td>
<td class="rate-content-cash text-right print_hide" data-table="本行現金買入">32.095</td>
<td class="rate-content-cash text-right print_hide" data-table="本行現金賣出">32.765</td>
<td class="rate-content-sight text-right print_hide" data-hide="phone" data-table="本行即期買入">
                        32.42
                    </td>
<td class="rate-content-sight text-right print_hide" data-hide="phone" data-table="本行即期賣出">
                        32.57
                    </td>
<td class="text-center print_hide phone-small-font" data-table="遠期匯率買入/賣出"><a href="/xrt/forward/USD" title="美金 遠期匯率">查詢</a></td>
<td class="text-center print_hide phone-small-font" data-table="歷史匯率"><a href="/xrt/history/USD?Lang=zh-TW" target="_blank" title="美金 歷史匯率 (另開視窗)">查詢</a></td>
<td class="text-right display_none_print_show print_width" data-table="本行現金買入">32.095</td>
<td class="text-right display_none_print_show print_width" data-table="本行現金賣出">32.765</td>
<td class="text-right display_none_print_show print_width" data-table="本行即期買入">32.42</td>
<td class="text-right display_none_print_show print_width" data-table="本行即期賣出">32.57</td>
</tr>
<tr>
<td class="currency phone-small-font" data-table="幣別">
<div>
<div class="sp-div sp-hong-kong-div">
<img alt="港幣" class="sp-img sp-hong-kong-img" src="/Content/images/sprite_lateral.png" title="幣別國旗"/>
</div>
<br class="visible-phone print_hide"/>
<div class="visible-phone print_hide">
                                港幣 (HKD)
                            </div>
<div class="hidden-phone print_show xrt-cur-indent">
                                港幣 (HKD)
                            </div>
</div>
</td>
<td class="rate-content-cash text-right print_hide" data-table="本行現金買入">4.005</td>
<td class="rate-content-cash text-right print_hide" data-table="本行現金賣出">4.209</td>
<td class="rate-content-sight text-right print_hide" data-hide="phone" data-table="本行即期買入">
                        4.126
                    </td>
<td class="rate-content-sight text-right print_hide" data-hide="phone" data-table="本行即期賣出">
                        4.196
                    </td>
<td class="text-center print_hide phone-small-font" data-table="遠期匯率買入/賣出"><a href="/xrt/forward/HKD" title="港幣 遠期匯率">查詢</a></td>
<td class="text-center print_hide phone-small-font" data-table="歷史匯率"><a href="/xrt/history/HKD?Lang=zh-TW" target="_blank" title="港幣 歷史匯率 (另開視窗)">查詢</a></td>
<td class="text-right display_none_print_show print_width" data-table="本行現金買入">4.005</td>
<td class="text-right display_none_print_show print_width" data-table="本行現金賣出">4.209</td>
<td class="text-right display_none_print_show print_width" data-table="本行即期買入">4.126</td>
<td class="text-right display_none_print_show print_width" data-table="本行即期賣出">4.196</td>
</tr>
<tr>
<td class="currency phone-small-font" data-table="幣別">
<div>
<div class="sp-div sp-england-div">
<img alt="英鎊" class="sp-img sp-england-img" src="/Content/images/sprite_lateral.png" title="幣別國旗"/>
</div>
<br class="visible-phone print_hide"/>
<div class="visible-phone print_hide">
                                英鎊 (GBP)
                            </div>
<div class="hidden-phone print_show xrt-cur-indent">
                                英鎊 (GBP)
                            </div>
</div>
</td>
<td class="rate-content-cash text-right print_hide" data-table="本行現金買入">40.44</td>
<td class="rate-content-cash text-right print_hide" data-table="本行現金賣出">42.56</td>
<td class="rate-content-sight text-right print_hide" data-hide="phone" data-table="本行即期買入">
                        41.335
                    </td>
<td class="rate-content-sight text-right print_hide" data-hide="phone" data-table="本行即期賣出">
                        41.965
                    </td>
<td class="text-center print_hide phone-small-font" data-table="遠期匯率買入/賣出"><a href="/xrt/forward/GBP" title="英鎊 遠期匯率">查詢</a></td>
<td class="text-center print_hide phone-small-font" data-table="歷史匯率"><a href="/xrt/history/GBP?Lang=zh-TW" target="_blank" title="英鎊 歷史匯率 (另開視窗)">查詢</a></td>
<td class="text-right display_none_print_show print_width" data-table="本行現金買入">40.44</td>
<td class="text-right display_none_print_show print_width" data-table="本行現金賣出">42.56</td>
<td class="text-right display_none_print_show print_width" data-table="本行即期買入">41.335</td>
<td class="text-right display_none_print_show print_width" data-table="本行即期賣出">41.965</td>
</tr>
<tr>
<td class="currency phone-small-font" data-table="幣別">
<div>
<div class="sp-div sp-australia-div">
<img alt="澳幣" class="sp-img sp-australia-img" src="/Content/images/sprite_lateral.png" title="幣別國旗"/>
</div>
<br class="visible-phone print_hide"/>
<div class="visible-phone print_hide">
                                澳幣 (AUD)
                            </div>
<div class="hidden-phone print_show xrt-cur-indent">
                                澳幣 (AUD)
                            </div>
</div>
</td>
<td class="rate-content-cash text-right print_hide" data-table="本行現金買入">21.51</td>
<td class="rate-content-cash text-right print_hide" data-table="本行現金賣出">22.29</td>
<td class="rate-content-sight text-right print_hide" data-hide="phone" data-table="本行即期買入">
                        21.725
                    </td>
<td class="rate-content-sight text-right print_hide" data-hide="phone" data-table="本行即期賣出">
                        22.07
                    </td>
<td class="text-center print_hide phone-small-font" data-table="遠期匯率買入/賣出"><a href="/xrt/forward/AUD" title="澳幣 遠期匯率">查詢</a></td>
<td class="text-center print_hide phone-small-font" data-table="歷史匯率"><a href="/xrt/history/AUD?Lang=zh-TW" target="_blank" title="澳幣 歷史匯率 (另開視窗)">查詢</a></td>
<td class="text-right display_none_print_show print_width" data-table="本行現金買入">21.51</td>
<td class="text-right display_none_print_show print_width" data-table="本行現金賣出">22.29</td>
<td class="text-right display_none_print_show print_width" data-table="本行即期買入">21.725</td>
<td class="text-right display_none_print_show print_width" data-table="本行即期賣出">22.07</td>
</tr>
<tr>
<td class="currency phone-small-font" data-table="幣別">
<div>
<div class="sp-div sp-canada-div">
<img alt="加拿大幣" class="sp-img sp-canada-img" src="/Content/images/sprite_lateral.png" title="幣別國旗"/>
</div>
<br class="visible-phone print_hide"/>
<div class="visible-phone print_hide">
                                加拿大幣 (CAD)
                            </div>
<div class="hidden-phone print_show xrt-cur-indent">
                                加拿大幣 (CAD)
                            </div>
</div>
</td>
<td class="rate-content-cash text-right print_hide" data-table="本行現金買入">23.35</td>
<td class="rate-content-cash text-right print_hide" data-table="本行現金賣出">24.26</td>
<td class="rate-content-sight text-right print_hide" data-hide="phone" data-table="本行即期買入">
                        23.68
                    </td>
<td class="rate-content-sight text-right print_hide" data-hide="phone" data-table="本行即期賣出">
                        24.01
                    </td>
<td class="text-center print_hide phone-small-font" data-table="遠期匯率買入/賣出"><a href="/xrt/forward/CAD" title="加拿大幣 遠期匯率">查詢</a></td>
<td class="text-center print_hide phone-small-font" data-table="歷史匯率"><a href="/xrt/history/CAD?Lang=zh-TW" target="_blank" title="加拿大幣 歷史匯率 (另開視窗)">查詢</a></td>
<td class="text-right display_none_print_show print_width" data-table="本行現金買入">23.35</td>
<td class="text-right display_none_print_show print_width" data-table="本行現金賣出">24.26</td>
<td class="text-right display_none_print_show print_width" data-table="本行即期買入">23.68</td>
<td class="text-right display_none_print_show print_width" data-table="本行即期賣出">24.01</td>
</tr>
<tr>
<td class="currency phone-small-font" data-table="幣別">
<div>
<div class="sp-div sp-singapore-div">
<img alt="新加坡幣" class="sp-img sp-singapore-img" src="/Content/images/sprite_lateral.png" title="幣別國旗"/>
</div>
<br class="visible-phone print_hide"/>
<div class="visible-phone print_hide">
                                新加坡幣 (SGD)
                            </div>
<div class="hidden-phone print_show xrt-cur-indent">
                                新加坡幣 (SGD)
                            </div>
</div>
</td>
<td class="rate-content-cash text-right print_hide" data-table="本行現金買入">23.5</td>
<td class="rate-content-cash text-right print_hide" data-table="本行現金賣出">24.41</td>
<td class="rate-content-sight text-right print_hide" data-hide="phone" data-table="本行即期買入">
                        23.97
                    </td>

In [ ]:
title= d.find_all('title')
print(title)

[<title>臺灣銀行牌告匯率</title>]

AttributeError: 'str' object has no attribute 'find_all'

In [ ]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

url=('https://rate.bot.com.tw/xrt?Lang=zh-TW')
response=requests.get(url)
soup=BeautifulSoup(contnent.text)

AttributeError: 'str' object has no attribute 'status_code'

In [ ]:
data = pd.read_html('https://rate.bot.com.tw/xrt?Lang=zh-TW')
df = data[0].iloc[:,0:5]
df.columns = ['幣別','現金本行買入','現金本行賣出','即期匯率本行買入','即期匯率本行賣出']
df['幣別'] = df['幣別'].str.split('  ').str[0]
print(df)

            幣別   現金本行買入   現金本行賣出 即期匯率本行買入 即期匯率本行賣出
0     美金 (USD)   32.095   32.765    32.42    32.57
1     港幣 (HKD)    4.005    4.209    4.126    4.196
2     英鎊 (GBP)    40.44    42.56   41.335   41.965
3     澳幣 (AUD)    21.51    22.29   21.725    22.07
4   加拿大幣 (CAD)    23.35    24.26    23.68    24.01
5   新加坡幣 (SGD)     23.5    24.41    23.97    24.19
6   瑞士法郎 (CHF)    35.39    36.59       36    36.39
7     日圓 (JPY)   0.1929   0.2057   0.1997   0.2047
8    南非幣 (ZAR)        -        -    1.751    1.841
9    瑞典幣 (SEK)     2.68      3.2     3.01     3.13
10    紐元 (NZD)    19.45     20.3    19.78    20.08
11    泰幣 (THB)   0.7638   0.9538   0.8742   0.9202
12  菲國比索 (PHP)   0.4892   0.6212        -        -
13   印尼幣 (IDR)  0.00158  0.00228        -        -
14    歐元 (EUR)    34.37    35.71   34.885   35.485
15    韓元 (KRW)  0.02175  0.02565        -        -
16   越南盾 (VND)  0.00103  0.00144        -        -
17   馬來幣 (MYR)    5.875      7.4        -        -
18   人民幣 (CNY)    4.365    4.527    4.432    4.492

In [29]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import sqlite3
from datetime import datetime

In [30]:
url='https://rate.bot.com.tw/xrt?Lang=zh-TW'
r=requests.get(url)
soup=BeautifulSoup(r.text,"html.parser")

In [31]:
cash_rate_buy = soup.find_all('td', class_='rate-content-cash text-right print_hide', attrs={'data-table': '本行現金買入'})
cash_rate_sell = soup.find_all('td', class_='rate-content-cash text-right print_hide', attrs={'data-table': '本行現金賣出'})
spot_rate_buy = soup.find_all('td', class_='rate-content-sight text-right print_hide', attrs={'data-table': '本行即期買入'})
spot_rate_sell = soup.find_all('td', class_='rate-content-sight text-right print_hide', attrs={'data-table': '本行即期賣出'})

In [32]:
#create a dataframe
data_list=[]


for i in range(len(currency)):
  currency_name=currency[i].text.strip()
  cash_buy=cash_buy_rate[i].text.strip()
  cash_sell=cash_sell_rate[i].text.strip()
  sight_buy=sight_buy_rate[i].text.strip()
  sight_sell=sight_sell_rate[i].text.strip()

In [33]:
 data_list.append([currency_name, cash_buy, cash_sell, spot_buy, spot_sell])

In [34]:
print(data_list)

[['人民幣 (CNY)', '4.373', '4.535', '4.44', '4.5']]

In [9]:
df=pd.DataFrame(data_list,columns=['幣別','現金本行買入','現金本行賣出','即期匯率本行買入','即期匯率本行賣出'])

In [10]:
df

          幣別 現金本行買入 現金本行賣出 即期匯率本行買入 即期匯率本行賣出
0  人民幣 (CNY)  4.373  4.535     4.44      4.5

            幣別 現金匯率本行買入 現金匯率本行賣出 即期匯率本行買入 即期匯率本行賣出                 更新日期
0     美金 (USD)   32.185   32.855    32.51    32.66  2024-07-10 14:49:41
1     港幣 (HKD)    4.016     4.22    4.137    4.207  2024-07-10 14:49:41
2     英鎊 (GBP)    40.59    42.71   41.485   42.115  2024-07-10 14:49:41
3     澳幣 (AUD)    21.58    22.36   21.795    22.14  2024-07-10 14:49:41
4   加拿大幣 (CAD)    23.45    24.36    23.78    24.11  2024-07-10 14:49:41
5   新加坡幣 (SGD)    23.59     24.5    24.06    24.28  2024-07-10 14:49:41
6   瑞士法郎 (CHF)    35.46    36.66    36.07    36.46  2024-07-10 14:49:41
7     日圓 (JPY)   0.1925   0.2053   0.1993   0.2043  2024-07-10 14:49:41
8    南非幣 (ZAR)        -        -    1.758    1.848  2024-07-10 14:49:41
9    瑞典幣 (SEK)     2.71     3.23     3.04     3.16  2024-07-10 14:49:41
10    紐元 (NZD)    19.33    20.18    19.66    19.96  2024-07-10 14:49:41
11    泰幣 (THB)   0.7679   0.9579   0.8783   0.9243  2024-07-10 14:49:41
12  菲國比索 (PHP)   0.4935   0.6255        -        -  2024-07-10 14:49:41
13   印尼幣 (IDR)  0.00168  0.00238        -        -  2024-07-10 14:49:41
14    歐元 (EUR)    34.47    35.81   34.985   35.585  2024-07-10 14:49:41
15    韓元 (KRW)  0.02181  0.02571        -        -  2024-07-10 14:49:41
16   越南盾 (VND)  0.00104  0.00145        -        -  2024-07-10 14:49:41
17   馬來幣 (MYR)    5.907    7.432        -        -  2024-07-10 14:49:41
18   人民幣 (CNY)    4.373    4.535     4.44      4.5  2024-07-10 14:49:41

In [39]:
import datetime
import pandas as pd
from bs4 import BeautifulSoup
import requests
import sqlite3
conn = sqlite3.connect('mydatabase.db')

content = requests.get("https://rate.bot.com.tw/xrt?Lang=zh-TW")
soup = BeautifulSoup(content.text,"html.parser")   #指定使用解析html的參數   html5lib html.parser

currency = soup.find_all('div', class_='visible-phone print_hide')

cash_rate_buy = soup.find_all('td', class_='rate-content-cash text-right print_hide', attrs={'data-table': '本行現金買入'})
cash_rate_sell = soup.find_all('td', class_='rate-content-cash text-right print_hide', attrs={'data-table': '本行現金賣出'})
spot_rate_buy = soup.find_all('td', class_='rate-content-sight text-right print_hide', attrs={'data-table': '本行即期買入'})
spot_rate_sell = soup.find_all('td', class_='rate-content-sight text-right print_hide', attrs={'data-table': '本行即期賣出'})

data = []
# .strip() 移除文本內容中的空白字符（空格、換行符等）
for i in range(len(currency)):
    currency_name = currency[i].text.strip()
    cash_buy = cash_rate_buy[i].text.strip()
    cash_sell = cash_rate_sell[i].text.strip()
    spot_buy = spot_rate_buy[i].text.strip()
    spot_sell = spot_rate_sell[i].text.strip()
    data.append([currency_name, cash_buy, cash_sell, spot_buy, spot_sell])


data

[['美金 (USD)', '32.185', '32.855', '32.51', '32.66'],
 ['港幣 (HKD)', '4.016', '4.22', '4.137', '4.207'],
 ['英鎊 (GBP)', '40.59', '42.71', '41.485', '42.115'],
 ['澳幣 (AUD)', '21.58', '22.36', '21.795', '22.14'],
 ['加拿大幣 (CAD)', '23.45', '24.36', '23.78', '24.11'],
 ['新加坡幣 (SGD)', '23.59', '24.5', '24.06', '24.28'],
 ['瑞士法郎 (CHF)', '35.46', '36.66', '36.07', '36.46'],
 ['日圓 (JPY)', '0.1925', '0.2053', '0.1993', '0.2043'],
 ['南非幣 (ZAR)', '-', '-', '1.758', '1.848'],
 ['瑞典幣 (SEK)', '2.71', '3.23', '3.04', '3.16'],
 ['紐元 (NZD)', '19.33', '20.18', '19.66', '19.96'],
 ['泰幣 (THB)', '0.7679', '0.9579', '0.8783', '0.9243'],
 ['菲國比索 (PHP)', '0.4935', '0.6255', '-', '-'],
 ['印尼幣 (IDR)', '0.00168', '0.00238', '-', '-'],
 ['歐元 (EUR)', '34.47', '35.81', '34.985', '35.585'],
 ['韓元 (KRW)', '0.02181', '0.02571', '-', '-'],
 ['越南盾 (VND)', '0.00104', '0.00145', '-', '-'],
 ['馬來幣 (MYR)', '5.907', '7.432', '-', '-'],
 ['人民幣 (CNY)', '4.373', '4.535', '4.44', '4.5']]

In [41]:

df = pd.DataFrame(data, columns=['幣別', '現金匯率本行買入', '現金匯率本行賣出', '即期匯率本行買入', '即期匯率本行賣出'])

df["更新日期"] = datetime.datetime.now()

print(df)

            幣別 現金匯率本行買入 現金匯率本行賣出 即期匯率本行買入 即期匯率本行賣出                       更新日期
0     美金 (USD)   32.185   32.855    32.51    32.66 2024-07-10 14:58:47.160933
1     港幣 (HKD)    4.016     4.22    4.137    4.207 2024-07-10 14:58:47.160933
2     英鎊 (GBP)    40.59    42.71   41.485   42.115 2024-07-10 14:58:47.160933
3     澳幣 (AUD)    21.58    22.36   21.795    22.14 2024-07-10 14:58:47.160933
4   加拿大幣 (CAD)    23.45    24.36    23.78    24.11 2024-07-10 14:58:47.160933
5   新加坡幣 (SGD)    23.59     24.5    24.06    24.28 2024-07-10 14:58:47.160933
6   瑞士法郎 (CHF)    35.46    36.66    36.07    36.46 2024-07-10 14:58:47.160933
7     日圓 (JPY)   0.1925   0.2053   0.1993   0.2043 2024-07-10 14:58:47.160933
8    南非幣 (ZAR)        -        -    1.758    1.848 2024-07-10 14:58:47.160933
9    瑞典幣 (SEK)     2.71     3.23     3.04     3.16 2024-07-10 14:58:47.160933
10    紐元 (NZD)    19.33    20.18    19.66    19.96 2024-07-10 14:58:47.160933
11    泰幣 (THB)   0.7679   0.9579   0.8783   0.9243 2024-07-10 14:58:47.160933
12  菲國比索 (PHP)   0.4935   0.6255        -        - 2024-07-10 14:58:47.160933
13   印尼幣 (IDR)  0.00168  0.00238        -        - 2024-07-10 14:58:47.160933
14    歐元 (EUR)    34.47    35.81   34.985   35.585 2024-07-10 14:58:47.160933
15    韓元 (KRW)  0.02181  0.02571        -        - 2024-07-10 14:58:47.160933
16   越南盾 (VND)  0.00104  0.00145        -        - 2024-07-10 14:58:47.160933
17   馬來幣 (MYR)    5.907    7.432        -        - 2024-07-10 14:58:47.160933
18   人民幣 (CNY)    4.373    4.535     4.44      4.5 2024-07-10 14:58:47.160933

In [42]:
df.to_sql('exchange_rates',conn,if_exists='append',index=False)

19

In [51]:
c=conn.cursor()
cursor=c.execute("select * from exchange_rates")

In [52]:
for row in cursor:
    print("幣別 =", row[0])
    print("現金匯率本行買入 =", row[1])
    print("現金匯率本行賣出 =", row[2])
    print("即期匯率本行買入 =", row[3])
    print("即期匯率本行賣出 =", row[4])
    print("更新日期 =", row[5], "\n")

幣別 = 美金 (USD)
現金匯率本行買入 = 32.185
現金匯率本行賣出 = 32.855
即期匯率本行買入 = 32.51
即期匯率本行賣出 = 32.66
更新日期 = 2024-07-10 14:54:21

幣別 = 港幣 (HKD)
現金匯率本行買入 = 4.016
現金匯率本行賣出 = 4.22
即期匯率本行買入 = 4.137
即期匯率本行賣出 = 4.207
更新日期 = 2024-07-10 14:54:21

幣別 = 英鎊 (GBP)
現金匯率本行買入 = 40.59
現金匯率本行賣出 = 42.71
即期匯率本行買入 = 41.485
即期匯率本行賣出 = 42.115
更新日期 = 2024-07-10 14:54:21

幣別 = 澳幣 (AUD)
現金匯率本行買入 = 21.58
現金匯率本行賣出 = 22.36
即期匯率本行買入 = 21.795
即期匯率本行賣出 = 22.14
更新日期 = 2024-07-10 14:54:21

幣別 = 加拿大幣 (CAD)
現金匯率本行買入 = 23.45
現金匯率本行賣出 = 24.36
即期匯率本行買入 = 23.78
即期匯率本行賣出 = 24.11
更新日期 = 2024-07-10 14:54:21

幣別 = 新加坡幣 (SGD)
現金匯率本行買入 = 23.59
現金匯率本行賣出 = 24.5
即期匯率本行買入 = 24.06
即期匯率本行賣出 = 24.28
更新日期 = 2024-07-10 14:54:21

幣別 = 瑞士法郎 (CHF)
現金匯率本行買入 = 35.46
現金匯率本行賣出 = 36.66
即期匯率本行買入 = 36.07
即期匯率本行賣出 = 36.46
更新日期 = 2024-07-10 14:54:21

幣別 = 日圓 (JPY)
現金匯率本行買入 = 0.1925
現金匯率本行賣出 = 0.2053
即期匯率本行買入 = 0.1993
即期匯率本行賣出 = 0.2043
更新日期 = 2024-07-10 14:54:21

幣別 = 南非幣 (ZAR)
現金匯率本行買入 = -
現金匯率本行賣出 = -
即期匯率本行買入 = 1.758
即期匯率本行賣出 = 1.848
更新日期 = 2024-07-10 14:54:21

幣別 = 瑞典幣 (SEK)
現金匯率本行買入 = 2.71
現金匯率本行賣出 = 3.23
即期匯率本行買入 = 3.04
即期匯率本行賣出 = 3.16
更新日期 = 2024-07-10 14:54:21

幣別 = 紐元 (NZD)
現金匯率本行買入 = 19.33
現金匯率本行賣出 = 20.18
即期匯率本行買入 = 19.66
即期匯率本行賣出 = 19.96
更新日期 = 2024-07-10 14:54:21

幣別 = 泰幣 (THB)
現金匯率本行買入 = 0.7679
現金匯率本行賣出 = 0.9579
即期匯率本行買入 = 0.8783
即期匯率本行賣出 = 0.9243
更新日期 = 2024-07-10 14:54:21

幣別 = 菲國比索 (PHP)
現金匯率本行買入 = 0.4935
現金匯率本行賣出 = 0.6255
即期匯率本行買入 = -
即期匯率本行賣出 = -
更新日期 = 2024-07-10 14:54:21

幣別 = 印尼幣 (IDR)
現金匯率本行買入 = 0.00168
現金匯率本行賣出 = 0.00238
即期匯率本行買入 = -
即期匯率本行賣出 = -
更新日期 = 2024-07-10 14:54:21

幣別 = 歐元 (EUR)
現金匯率本行買入 = 34.47
現金匯率本行賣出 = 35.81
即期匯率本行買入 = 34.985
即期匯率本行賣出 = 35.585
更新日期 = 2024-07-10 14:54:21

幣別 = 韓元 (KRW)
現金匯率本行買入 = 0.02181
現金匯率本行賣出 = 0.02571
即期匯率本行買入 = -
即期匯率本行賣出 = -
更新日期 = 2024-07-10 14:54:21

幣別 = 越南盾 (VND)
現金匯率本行買入 = 0.00104
現金匯率本行賣出 = 0.00145
即期匯率本行買入 = -
即期匯率本行賣出 = -
更新日期 = 2024-07-10 14:54:21

幣別 = 馬來幣 (MYR)
現金匯率本行買入 = 5.907
現金匯率本行賣出 = 7.432
即期匯率本行買入 = -
即期匯率本行賣出 = -
更新日期 = 2024-07-10 14:54:21

幣別 = 人民幣 (CNY)
現金匯率本行買入 = 4.373
現金匯率本行賣出 = 4.535
即期匯率本行買入 = 4.44
即期匯率本行賣出 = 4.5
更新日期 = 2024-07-10 14:54:21

幣別 = 美金 (USD)
現金匯率本行買入 = 32.185
現金匯率本行賣出 = 32.855
即期匯率本行買入 = 32.51
即期匯率本行賣出 = 32.66
更新日期 = 2024-07-10 14:58:47.160933

幣別 = 港幣 (HKD)
現金匯率本行買入 = 4.016
現金匯率本行賣出 = 4.22
即期匯率本行買入 = 4.137
即期匯率本行賣出 = 4.207
更新日期 = 2024-07-10 14:58:47.160933

幣別 = 英鎊 (GBP)
現金匯率本行買入 = 40.59
現金匯率本行賣出 = 42.71
即期匯率本行買入 = 41.485
即期匯率本行賣出 = 42.115
更新日期 = 2024-07-10 14:58:47.160933

幣別 = 澳幣 (AUD)
現金匯率本行買入 = 21.58
現金匯率本行賣出 = 22.36
即期匯率本行買入 = 21.795
即期匯率本行賣出 = 22.14
更新日期 = 2024-07-10 14:58:47.160933

幣別 = 加拿大幣 (CAD)
現金匯率本行買入 = 23.45
現金匯率本行賣出 = 24.36
即期匯率本行買入 = 23.78
即期匯率本行賣出 = 24.11
更新日期 = 2024-07-10 14:58:47.160933

幣別 = 新加坡幣 (SGD)
現金匯率本行買入 = 23.59
現金匯率本行賣出 = 24.5
即期匯率本行買入 = 24.06
即期匯率本行賣出 = 24.28
更新日期 = 2024-07-10 14:58:47.160933

幣別 = 瑞士法郎 (CHF)
現金匯率本行買入 = 35.46
現金匯率本行賣出 = 36.66
即期匯率本行買入 = 36.07
即期匯率本行賣出 = 36.46
更新日期 = 2024-07-10 14:58:47.160933

幣別 = 日圓 (JPY)
現金匯率本行買入 = 0.1925
現金匯率本行賣出 = 0.2053
即期匯率本行買入 = 0.1993
即期匯率本行賣出 = 0.2043
更新日期 = 2024-07-10 14:58:47.160933

幣別 = 南非幣 (ZAR)
現金匯率本行買入 = -
現金匯率本行賣出 = -
即期匯率本行買入 = 1.758
即期匯率本行賣出 = 1.848
更新日期 = 2024-07-10 14:58:47.160933

幣別 = 瑞典幣 (SEK)
現金匯率本行買入 = 2.71
現金匯率本行賣出 = 3.23
即期匯率本行買入 = 3.04
即期匯率本行賣出 = 3.16
更新日期 = 2024-07-10 14:58:47.160933

幣別 = 紐元 (NZD)
現金匯率本行買入 = 19.33
現金匯率本行賣出 = 20.18
即期匯率本行買入 = 19.66
即期匯率本行賣出 = 19.96
更新日期 = 2024-07-10 14:58:47.160933

幣別 = 泰幣 (THB)
現金匯率本行買入 = 0.7679
現金匯率本行賣出 = 0.9579
即期匯率本行買入 = 0.8783
即期匯率本行賣出 = 0.9243
更新日期 = 2024-07-10 14:58:47.160933

幣別 = 菲國比索 (PHP)
現金匯率本行買入 = 0.4935
現金匯率本行賣出 = 0.6255
即期匯率本行買入 = -
即期匯率本行賣出 = -
更新日期 = 2024-07-10 14:58:47.160933

幣別 = 印尼幣 (IDR)
現金匯率本行買入 = 0.00168
現金匯率本行賣出 = 0.00238
即期匯率本行買入 = -
即期匯率本行賣出 = -
更新日期 = 2024-07-10 14:58:47.160933

幣別 = 歐元 (EUR)
現金匯率本行買入 = 34.47
現金匯率本行賣出 = 35.81
即期匯率本行買入 = 34.985
即期匯率本行賣出 = 35.585
更新日期 = 2024-07-10 14:58:47.160933

幣別 = 韓元 (KRW)
現金匯率本行買入 = 0.02181
現金匯率本行賣出 = 0.02571
即期匯率本行買入 = -
即期匯率本行賣出 = -
更新日期 = 2024-07-10 14:58:47.160933

幣別 = 越南盾 (VND)
現金匯率本行買入 = 0.00104
現金匯率本行賣出 = 0.00145
即期匯率本行買入 = -
即期匯率本行賣出 = -
更新日期 = 2024-07-10 14:58:47.160933

幣別 = 馬來幣 (MYR)
現金匯率本行買入 = 5.907
現金匯率本行賣出 = 7.432
即期匯率本行買入 = -
即期匯率本行賣出 = -
更新日期 = 2024-07-10 14:58:47.160933

幣別 = 人民幣 (CNY)
現金匯率本行買入 = 4.373
現金匯率本行賣出 = 4.535
即期匯率本行買入 = 4.44
即期匯率本行賣出 = 4.5
更新日期 = 2024-07-10 14:58:47.160933